### ISSUE TITLE
Create: Landing Page: "You're not authorized" error

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#1041]
**Describe the bug**
I run into "You're not authorized" error when I land on Create page. It shows up before the page is even fully loaded. 

**To Reproduce**
1. Go to Create menu: https://jicloud.org/jig/edit/gallery
2. See error, "You're not authorized" error notification

**Expected behavior**
I expect to land on the page without encountering an error.

**Screenshots**
![019_Create_Create_NotAuthorized](https://user-images.githubusercontent.com/74170693/117602028-b98b1580-b11d-11eb-9406-d7ecbdd663d7.png)

**Additional context**
- This error crops up in other instances on this page too. 
- When I click "Ok" I am able to view the page
- When I refresh the page I run into the same issue

**Comment by dani-ji** [comment]
@esteels does this occur even after you login?

**Comment by dani-ji** [comment]
Describe the bug
I run into a "You're not authorized" error when I try to change any of the fields in the "My Recent JIGS" section of the page. See issue #1041

To Reproduce
Steps to reproduce the behavior:

Go to Create landing page. Encounter initial error (see #1041) + click ok to view page.
Click in Search field OR click dropdown menu and change My Recent JIG settings.
See error "You're not authorized" notification
Expected behavior
I expect to be able to use the fields to search and change My Recent JIGs setting without getting an error.

Screenshots
021_Create_Create1_SearchNotAuthorized

**Comment by esteels** [comment]
> @esteels does this occur even after you login?

@dani-ji it's hard for me to tell. I can only access this page from the provided link: https://jicloud.org/jig/edit/gallery 

Whereas logging in via https://jicloud.org/user/login leads me to a screen that looks like this:

![019_B_Create_Create_NotAuthorized_Login](https://user-images.githubusercontent.com/74170693/118221743-3a168280-b44c-11eb-8e08-086c52bd37b0.png)

(see issue #1040)

**Comment by MendyBerger** [comment]
Can't reproduce, probably has been fixed already
