### ISSUE TITLE
Update Profile API

### ISSUE THREAD

**Issue by dakom** [ji-devs/ji-cloud#1146]
Currently it's possible to create a user's profile the first time, but not possible to update later

**Comment by MendyBerger** [comment]
@rrcwang any reason email address is not included?

**Comment by rrcwang** [comment]
> @rrcwang any reason email address is not included?

The user email what we use to identify the user for authentication. It's more accurate to say that a profile is "associated" with an email rather than email being a part of one.

It makes sense that we should let users change their email, however this would be a bigger change needing re-verification and handling different types of user auths.

If this is required we can reopen this issue/create a new one.
