### ISSUE TITLE
Change AGE GROUP labels in the database

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1202]
1. Rename 'University' to 'Pre-K', 
2. Reorder so that Pre-K is the first in the list
3. For every image that was tagged 'All ages', select all groups.
4. Delete 'All ages'.

**Comment by dakom** [comment]
Note, final list is:

Pre-K
Kindergarten
Elementary school
Middle school
High school

**Comment by dakom** [comment]
As discussed on Slack, in order to avoid breakage we are not going to delete existing AGE GROUPS. Rather, the process will be this:

1. For everything that previously had "all ages" selected, do the following:
    1. Select all the other AgeRangeId's
    2. Deselect "all ages"

2. After that is done, rename "all ages" to "Pre-K" so that we are repurposing instead of deleting
3. Patch up the ordering so that it's correct

This would make the final list:

Pre-K
Kindergarten
Elementary school
Middle school
High school
University

@corinnewo all good?

**Comment by corinnewo** [comment]
In this order, the Pre-K will not be selected if ALL AGES were selected. Does it not make sense to rename University to Pre-K, and then after running the utility change **All Ages** back to University again. 
Chana does not want university at all, so we can hide it from view in the admin?

**Comment by dakom** [comment]
I don't think anything in University was previously selected, so in either case Pre-K wouldn't be selected.

If Chana doesn't want university at all then we can't do this, it needs to be properly deleted from the database

**Comment by dakom** [comment]
I've updated the flow to note that everything must be selected (don't de-select "all ages")

**Comment by dakom** [comment]
This is done. University *is* included. As discussed if we genuinely need to delete it, we'll need to do so carefully and a new issue should be opened for that
