### ISSUE TITLE
Change Affiliation labels in the database

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1203]
1. For every image that was tagged 'show me everything', select all groups.
2. Delete 'show me everything'.

**Comment by dakom** [comment]
As discussed on Slack, in order to avoid breakage we are not going to delete existing AFFILIATIONS. Rather, the process will be this:

1. For everything that previously had "Show me everything" selected, do the following:
    1. Select all the other AffiliationId's
    2. Deselect "Show me everything"

2. After that is done, rename "Show me everything" to "Traditional" so that we are repurposing instead of deleting
3. Patch up the ordering so that it's correct

This would make the final list:

Traditional
No religious
Reform/Liberal
Orthodox
Conservative
Israeli secular
Charedi

@corinnewo all good?

**Comment by corinnewo** [comment]
I would put the Israeli secular after No religion, before Reform. It is not correct breaking the continuum. In fact, this should be the order:

No religious content
Israeli secular
Traditional
Reform/Liberal
Conservative
Orthodox
Charedi

Possibly will hide the 'Traditional' - but you need to be careful whether it will be checked if you do it in the order you suggest. How will you know that it should be checked?

**Comment by dakom** [comment]
good point about needing to make sure everything is checked if "Show me everything" was previously checked, I updated the flow

yeah, ordering is fine
