### ISSUE TITLE
fix ISE (500) when replacing image in global library or uploading to user library (via user::image::Upload)

### ISSUE THREAD

**Issue by dakom** [ji-devs/ji-cloud#1246]
Calling [Upload](https://docs.sandbox.jicloud.org/crate/shared/api/endpoints/image/struct.Upload.html) with a pre-existing image results in a `500`. It's supposed to replace the existing image.

**Comment by rrcwang** [comment]
I suspect this is the same issue as #1209, and it's throwing 500 instead of 401 because I disabled the error handling logic when we first came across this. Going to leave both issues open for now just in case.

I couldn't replicate this through the admin panel on release, even when replacing images. I was able to replicate it **once** on sandbox before it went away again.

The logging on sandbox has been updated to spit out the entire response from GCS now, which will help identify *if and when* this happens again.

**Comment by dakom** [comment]
Note that this happens when adding a new image on Sandbox

**Comment by dakom** [comment]
Some more info (not definitive, needs more sleuthing!): 

It seems that the deployed services are _always_ trying to get the google credentials via the `GOOGLE_APPLICATION_CREDENTIALS_DEV_*` env variable, and rather, it should only use that for the credentials for local development (hence the `_DEV_` naming)

This might be causing a problem here, since those credentials could be out of date and not include all the required permissions for creating signed urls etc.

Suggestion - force the server to only use the `get_google_token_from_metaserver()` approach when deploying remotely

(I'm not 100% sure if that's supposed to work... my rough understanding is it _should_ by way of the Cloud Run service account having access to that...)

A couple relevant links in the source:

https://github.com/ji-devs/ji-cloud/blob/3e928be4dae04691441e2b27c4489a6aad5e9c3e/backend/core/src/settings.rs#L367

 https://github.com/ji-devs/ji-cloud/blob/3e928be4dae04691441e2b27c4489a6aad5e9c3e/backend/core/src/google.rs#L30
