### ISSUE TITLE
Add an Activity - correct the activity icons

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1291]
On the screen with the list of activities that you can drag in, please change

1. the icon for 'Find the Pair' - Gali changed it to be like cards - https://zpl.io/VYlz7Je 
![image](https://user-images.githubusercontent.com/16290361/129039481-005fd5b2-8182-4980-809a-16a5fe3a0bc2.png)

2. the icon for 'Drag and Drop' - 
![image](https://user-images.githubusercontent.com/16290361/129039548-79ff13d0-b3d0-407b-9a4b-1456b3b59b96.png)

![image](https://user-images.githubusercontent.com/16290361/129038810-704a4f84-d4de-4303-bdcf-83cf385dbee7.png)

**Comment by dakom** [comment]
Note: these icons are all in dropbox and can just be replaced (in `ui/entry/jig/modules`). The naming convention is the module name followed by an optional `-hover` or `-drag` and `.svg` extension.

I tried to export what's there, but `card-quiz-drag.svg` couldn't be exported because it isn't grouped and I don't have the XD

Actually, looking at it, they might _all_ need to be grouped to include the whitespace, otherwise they'll just all center

@corinnewo I'm assigning this back to you as a stand-in for Gali ;)
