### ISSUE TITLE
After duplication of a module - user should get to the play settings of the new activity

### ISSUE THREAD

**Issue by GaliShapira** [ji-devs/ji-cloud#1374]
Flow - after duplication of a module, must open up the new module after the data - to the play settings.

**Comment by dakom** [comment]
There's also a conflict, potentially, with the editor state that we do serialize.

For example, we have a brief that we preserve the completed steps and the current step in the wizard. If the play settings aren't that step, then there's a conflict.

**Comment by corinnewo** [comment]
I think that Gali is referring to the 'save data as', which would only be the card modules. It makes sense that you are saving the data, so you do not need to go through those steps. But perhaps when you 'duplicate as' at the end of a module, at the very least, the new module should open up. I know that you are both working on this flow at the end of a module.

**Comment by dakom** [comment]
Converting modules is lossy. We can't preserve the player settings (or editor state in general) because they are different between modules, only the raw data of the content.

So if it's just about opening the module when it's duplicated, then it's a bug in https://github.com/ji-devs/ji-cloud/issues/1273 and this is a duplicate, will re-open that other issue and mark this as duplicate
