### ISSUE TITLE
Video module does not play in the player

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1380]
**Describe the bug**
I created a JIG (https://jigzi.org/jig/edit/fca7f48e-fc20-11eb-b262-23b9c8b0053d) with 2 videos. Last week, when I created the JIG, it played well. Today, from the Preview JIG on JIG panel, the video screen is simply a big red screen!
Also from the post-publish screen to play the JIG, the same thing happens.

**To Reproduce**
1. Go to JIG fca7f48e-fc20-11eb-b262-23b9c8b0053d
2. Play - go to second or third module
3. See error

**Expected behavior**
Play the video!

**Screenshots**
![image](https://user-images.githubusercontent.com/16290361/130028752-0aad369a-ea85-422a-bd00-15f5b41f2d48.png)
![image](https://user-images.githubusercontent.com/16290361/130029152-d6dad657-1840-4e9d-95e2-9f15c3aa23d1.png)

**Comment by corinnewo** [comment]
I went back in and deleted the module that was not working, and created a new video module, which is now playing OK. Seems like it must be connected with something that changed in the player or JIG editor.

**Comment by dakom** [comment]
It could also be https://github.com/ji-devs/ji-cloud/issues/1381

**Comment by dakom** [comment]
however, we do have one glaring problem in our pipeline which may have caused this as well - changes to the module data structure require manually implementing a migration and there is no automatic way to catch this at the moment.

this is solvable by having more robust integration tests, and I have some ideas on how we can automate that for all the modules, but I think it's better to leave this as a QA thing for now since we don't change the module data structures very often.

**Comment by MendyBerger** [comment]
Looks like the server is responding with an error 500, not sure how to proceed here

**Comment by corinnewo** [comment]
I think it is now working
