### ISSUE TITLE
Text placed at the bottom of the screen gets covered by player controls

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1382]
I created a video module and placed text at the bottom, under the video. In the player, the text gets covered by the controls.
We had spoken about having a grid on the design screen to show where content should be placed. Do we have this?

![image](https://user-images.githubusercontent.com/16290361/130031660-64791284-6acd-41dc-9e98-0f3bee01b7e4.png)

This is what the content area looks like: 
![image](https://user-images.githubusercontent.com/16290361/130031920-11dd166c-2e7d-49ed-ac41-81c7668720dc.png)

**Comment by corinnewo** [comment]
Also, perhaps another problem, I see that the player size cuts out the bottom of the canvas....@MendyBerger - is there anything we can do about that?

**Comment by dakom** [comment]
re: grid, we did speak about it and I believe the decision was to do it but post-mvp. I don't see an issue for it in the Future milestone though... please create one and link to the Zeplin if possible.

**Comment by GaliShapira** [comment]
@corinnewo @dakom 
This is the link to the grid flow:
https://zpl.io/2p3Ajly

1.	First - The user see the grid, he can align to and he sees the frame.
2.	If the user trying to place something outside of the grid then you see the next screen, suggesting the user not to place outside the frame. (When the user didnt leave the mouse)
3.	If the user did place it outside the frame, we have a notification.
We said that we dont want to prevent the user from doing that, because there might be use cases where its needed.

**Comment by dakom** [comment]
@corinnewo from what I saw earlier, there is a bug with the video which is totally separate from the grid...

**Comment by corinnewo** [comment]
Yes - I made a different ticket for that problem: #1392 

I also added in a new ticket for the grid issue: #1383 

Will close this ticket now.
