### ISSUE TITLE
While creating - need a grid to show border limitations and to be able to align

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1383]
As you are creating a JIG, there should be a grid to help with placement in the screen, as well as to show the border limitations. 
Please add in the area around the player controls so that creator knows not to place there.
https://zpl.io/an3RQKO

**Comment by GaliShapira** [comment]
This is the link to the grid flow:
https://zpl.io/2p3Ajly

1.	First - The user see the grid, he can align to and he sees the frame.
2.	If the user trying to place something outside of the grid then you see the next screen, suggesting the user not to place outside the frame. (When the user didnt leave the mouse)
3.	If the user did place it outside the frame, we have a notification.
We said that we dont want to prevent the user from doing that, because there might be use cases where its needed.

**Comment by dakom** [comment]
I think a grid is a great idea, as an enhancement to guide users, but moving the controlbar out of the way has its own [set of problems](https://github.com/ji-devs/ji-cloud/issues/2040#issuecomment-999640757)

**Comment by corinnewo** [comment]
@GaliShapira Please can you attach an svg of the grid that @MendyBerger needs for this? See https://zpl.io/a8n1vKE - is this the final grid to place? Thanks!

**Comment by GaliShapira** [comment]
I attach 2 svg's. One is including the transparent area, I am not sure it would work, if not create it with the code
[SVGs.zip](https://github.com/ji-devs/ji-cloud/files/7863645/SVGs.zip)
.

**Comment by corinnewo** [comment]
Thanks @GaliShapira !
