### ISSUE TITLE
Publish - the thumbnail needs a border

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1483]
When you publish a JIG when the cover is empty and the them was default white, there is no definition of where the thumbnail might even be! Need a border. In Zeplin - there is no border. (Perhaps use this opportunity to add in the edit button to open the cover too?)

![image](https://user-images.githubusercontent.com/16290361/131491079-4896f05a-282c-44c5-b754-f3b12fb40129.png)

**Comment by GaliShapira** [comment]
@corinnewo @MendyBerger 
Mendy, can you kindly add a gray outline: #A9B1B5, 1-pixel width to the thumbnails of the activities? Make sure that the same border is seen on the JIG thumbnail on the publish page, on JIGs in search results and in JIG creator page. SO that if there is a white background we see a border line in all of these places.

Ps see the updated screen: https://zpl.io/V4rXdGQ
[Archive.zip](https://github.com/ji-devs/ji-cloud/files/7089560/Archive.zip)

**Comment by corinnewo** [comment]
@GaliShapira THanks for this. Are we not going to also add an 'Edit cover' button on the publish dialog?

**Comment by GaliShapira** [comment]
Yes, I will upload it later on.

**Comment by MendyBerger** [comment]
Resolved in 0bc60557263f1255fc0fec30bfd5c2663873207a
