### ISSUE TITLE
After publish - Sharing options display in tiny dialog

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1490]
Please position this dialog further up so that you can see the options.
See https://zpl.io/bzQw7Y8, to place the dialog higher up!

![image](https://user-images.githubusercontent.com/16290361/131656177-df315e11-6875-4669-93d7-c0327f6f017a.png)

**Comment by mastapegs** [comment]
Is this still an issue? I tried to recreate it since I was doing some work in the same area, but the sharing options are not moved to the bottom like shown in the image

If it is still happening, what steps do you take to recreate this?

![image](https://user-images.githubusercontent.com/13839150/149549858-d462b3f1-b2a3-4c1e-8f8f-3500dd804c43.png)

**Comment by corinnewo** [comment]
@mastapegs Yay! Finally fixed! Thanks - I will close this issue now!
