### ISSUE TITLE
Overlay/background cannot be removed or hidden

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1623]
This is part of the design spec in Zeplin that has not been implemented. It is essential to implement, as without being able to remove or hide an overlay, you have to remove the whole activity to get rid of the overlay, and start again!

See example of hide toggle here: https://zpl.io/aM6ndNm
Also, we wanted a right-click on a background image to remove background image, remove overlay, etc: https://zpl.io/b6GGr7m

@dakom never got to do this, but it is really important to do!

**Comment by dakom** [comment]
duplicate of https://github.com/ji-devs/ji-cloud/issues/1325... but I'll close that other issue in favor of this

**Comment by corinnewo** [comment]
So then, at the very least, add in the toggle to hide the overlay in the left hand panel, which was not implemented from the initial zeplin: https://zpl.io/aM6ndNm

**Comment by dakom** [comment]
That is complicated since it requires the image search component to "know about" the module structure (so it can show the current setting) and also requires updating the modules to have a flag to indicate whether the background overlay is visible or not.

I also find it confusing since it doesn't apply to the search itself

Simplest is just to make that toggle a button with a trashcan icon or something, and it could always be active even if there is no current overlay

**Comment by corinnewo** [comment]
Closing in favour of #2590
