### ISSUE TITLE
Registration (Sign up)  - text needs correction

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1626]
Currently, after sending the email, the following screen is displayed:
![image](https://user-images.githubusercontent.com/16290361/136938336-ba573318-005f-4a4b-bc57-f50949433330.png)

Please change to (not capitalization and punctuation):

**We just sent you an email**
Please open the email and click on the Verification button. If you cannot see the email in your inbox, check your promotion or spam folders.

I didn’t receive an email. Please send again.   (button)

**Comment by mastapegs** [comment]
# StoryBook render of email sent w/ changes

![image](https://user-images.githubusercontent.com/13839150/147714170-be0b2cad-5f4d-44a9-92fa-479f35bedd01.png)

**Comment by corinnewo** [comment]
@mastapegs Please don't go according to any Storybook text! I think that this text was correct in the live version already.

Our copywriter, Chaykee, has the final texts in this document: https://docs.google.com/spreadsheets/d/1jKGbjX7Tvy3ck-HbKiENAdIfBKh6YptO/edit?usp=sharing&ouid=102794875032798378521&rtpof=true&sd=true

Heading here should be: 
**Woohoo! We just sent you an email.**

Body: 
**You're one step closer to the Jigzi family! Please check your inbox and click the verification button.
If you don't see it within minutes, check your filters and spam folders.**

Button:
Didn't receive our email? Send again

Please revert to this text.
Thanks!

**Comment by mastapegs** [comment]
This looks like the issue is ready to be closed then. Below is a picture from sandbox showing the email sent. One question I have that there may be a difference is the `Send again` button. Should the entire text ("Didn't receive our email? Send again") be a button, or should it remain as is @corinnewo?

If the image below looks good, then this ticket is ready to close.

![image](https://user-images.githubusercontent.com/13839150/147776527-9273604e-b060-4a71-9646-dd0e5e1041b1.png)

**Comment by MendyBerger** [comment]
Like this is great! Thanks
