### ISSUE TITLE
Add Jiggling text for Sound/ Jig Settings?

### ISSUE THREAD

**Issue by chayaml** [ji-devs/ji-cloud#1710]
Hi @corinnewo ,

When creating a Jig, it took me a while to notice - a few creations in -  that on top of the kebab menu there is a _settings icon_ where I can add background music and feedback effects, etc. I don't know if it's just me since I thought the sound features weren't added yet, or if a user will also not pick up on the sound feature/ how to get to it. 

Perhaps we should add a jiggling text to explain this?
or
When a user previews their Jig and tries to click on the music icon (that's greyed out since no sound selected), a jiggling text will appear-  "go to settings to add sound"

![Screen Shot 2021-10-18 at 11 03 11 PM](https://user-images.githubusercontent.com/78186896/137837944-38c38c84-707b-47cf-a1c7-e7599181f793.png)

What do you think?

**Comment by corinnewo** [comment]
@chayaml You are quite right - users are not going to see this if it is not pointed out to them.
Gali has actually designed a new panel that has the settings icon on the closed panel, so that it would be more noticeable. https://zpl.io/2En3vRl

I have a ticket for Mendy to implement - I will make it a higher priority. I will also try and make sure that we have texts pointing it out.

**Comment by MendyBerger** [comment]
Resolved in 96f56a85
