### ISSUE TITLE
Image Search: by add image with no backgrounds default, backgrounds show up as stickers and the bounding box is not visible

### ISSUE THREAD

**Issue by chayaml** [ji-devs/ji-cloud#1861]
Inside the filter dropdown:

• In add background, checkbox of _background only_ is marked as default
• In add image, checkbox of _no background_ is marked as default

By add images (no backgrounds), backgrounds come up in the search as stickers ( large scale - size of canvas) and the bounding box is not visible.

- are backgrounds supposed to come up as stickers in the image search?
- if yes can their size be reduced so it is obvious that it is a sticker?

![Screen Shot 2021-11-08 at 2 56 44 PM](https://user-images.githubusercontent.com/78186896/140814716-108cd997-fa9a-4689-9959-701ecf7c646d.png)
![Screen Shot 2021-11-08 at 3 28 15 PM](https://user-images.githubusercontent.com/78186896/140814785-1a8a8dcc-1ae4-41a7-a8d9-fefde56511e8.png)

Related to #1554

**Comment by corinnewo** [comment]
@chayaml  Why are backgrounds showing up in the search results for images, when filter is set to no backgrounds? We need to check the settings for these images.
@MendyBerger Can you set image size for 'background' images that are being loaded as stickers at 90% of their size, so that they are clearly stickers and bounding box can be seen?
