### ISSUE TITLE
Legacy conversion of ASK A QUESTION is crashing

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1898]
@dakom
I am getting an error for the ASK A QUESTION - immediately shows the OOPS! screen.
![image](https://user-images.githubusercontent.com/16290361/141435267-19e9764a-b072-4f86-83eb-ec36e332b520.png)

_Originally posted by @corinnewo in https://github.com/ji-devs/ji-cloud/discussions/1780#discussioncomment-1630289_

**Comment by RickyLB** [comment]
Merged a fix for this deserialization problem

**Comment by dakom** [comment]
@RickyLB I don't think this would have been something on your side.. all the legacy stuff doesn't get merged into the db. I think I just need to regenerate this game (which is a totally separate process from the usual stuff)

Am I missing something?

**Comment by dakom** [comment]
This should be fixed now, just needed to re-generate the game.

I also started work on having a CDN endpoint for the legacy content, so the URLs in the discussion page changed slightly (no &example=true ... if you leave &example=true on, e.g. via an old bookmark, it will hit the dropbox version which has _not_ been updated since I don't have dropbox at the moment)
