### ISSUE TITLE
Add email change for Oauth users

### ISSUE THREAD

**Issue by RickyLB** [ji-devs/ji-cloud#1911]
Email change for non Oauth users is implemented, but not for Oauth.

**Comment by MendyBerger** [comment]
@RickyLB how would this be implemented?

**Comment by RickyLB** [comment]
I had made this issue with the intentions that changing https://github.com/ji-devs/ji-cloud/issues/1550 applies to OAuth and not just basic. 
 
Also, was only thinking about the case of switching between OAuth accounts. In the database, it seems we would just have to change the `google_id` in the `user_auth_google` table according to user id, and also switch the email string in `user_email` table. I'm unsure what the frontend had planned for OAuth to OAuth account but my thoughts would be to: 

- send a verification email to the current email in the database about the email change
- after confirmation from current email, another verification email gets sent to the new email.

**Comment by MendyBerger** [comment]
Even for switching from one OAuth account to another I can see the following problems:

- What if the user wants to switch from one OAuth provider to another (we might be interested in adding other providers in the future e.g. Apple, Facebook, etc.).
- We need to notify the OAuth provider somehow that we released the old email, otherwise it will still be connected to us from their end.

Unless we have answers to these questions, I think you should hold off on this until the need arises.

**Comment by RickyLB** [comment]
Okay, will close this issue for now.
