### ISSUE TITLE
Card games - sound effects for card flips and answers

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2060]
I have put the sound effects for the card games that I was given in ...ji-cloud-media>audio>module>cards
https://www.dropbox.com/sh/nqv617gwvfgqc4f/AACjVChAa43UndeCpAkAsBDda?dl=0

There are 3 options for flip - choose one that sounds good. I think the other card sounds are for right and wrong. 

Gali also had CSS effects from https://ianlunn.github.io/Hover/#effects for right and wrong.

Card games: 

- [x] Card quiz
- [x] Memory
- [x] Matching
- [x] Flashcards

Extra:

- [x] Right/wrong css effects

**Comment by johnnynotsolucky** [comment]
@corinnewo the sound effects have been implemented for card-quiz, memory, flashcards and matching games. For each game there are slightly different variations on how the side-effects are played:

#### Card quiz

- Card flip sound is played only when a player makes an incorrect choice;
- If the player makes a correct choice - the positive sound is played.

#### Memory

- Card flip effect for the first card chosen, and then
- Positive or negative effect when the 2nd card is chosen based on the correctness.

#### Flashcards

- Card flip sound is played when a player taps a card and it flips, but not when the card flips back to its original state.
- This game has no right/wrong answers, so no other sound effects were used.

#### Matching

- Positive effect when a card is placed in the correct block;
- Negative effect only if a card is placed in the incorrect block - if the card is dropped outside of the blocks, no effect is played.
  - I made it so that dropping a card outside of a block doesn't play because perhaps the player wanted to change their card and it felt like playing a negative effect would be inappropriate.

**Comment by johnnynotsolucky** [comment]
Animation effect applied to the card-quiz when the correct answer is chosen (#2159)
