### ISSUE TITLE
Creating a resource-cover returns an error 500

### ISSUE THREAD

**Issue by MendyBerger** [ji-devs/ji-cloud#2093]
Calling `endpoints::jig::module::Create` with `ModuleKind::ResourceCover` in body the server returns an error 500

```bash
curl 'https://api.sandbox.jigzi.org/v1/jig/ed32a8f0-6435-11ec-82f1-8be61e5a70bc/draft/module' \
  -H 'authority: api.sandbox.jigzi.org' \
  -H 'authorization: [???]' \
  -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.56 Safari/537.36' \
  -H 'content-type: application/json' \
  -H 'accept: */*' \
  -H 'sec-gpc: 1' \
  -H 'origin: http://localhost:4104' \
  -H 'sec-fetch-site: cross-site' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-dest: empty' \
  -H 'referer: http://localhost:4104/' \
  -H 'accept-language: en-US,en;q=0.9' \
  --data-raw '{"body":{"resourceCover":{"content":{"editor_state":{"step":"One","steps_completed":[]},"base":{"instructions":{"text":null,"audio":null},"theme":"Jig","backgrounds":{"layer_1":null,"layer_2":null},"stickers":[]}}}}}' \
  --compressed
```

**Comment by johnnynotsolucky** [comment]
@MendyBerger the error is because the ResourceCover is being added and no Cover exists yet.

There is a constraint on the `jig_data_module` table which ensures that the module is either a `ModuleKind::Cover` at index 0 or anything else at index > 0:

https://github.com/ji-devs/ji-cloud/blob/b9a9daa95df85daa4a7424e7bf66a89ffd599331/backend/api/migrations/20210923001312_jig-and-module-draft-publish-live-api.sql#L78-L78

I'm not up-to-date with the requirements, but it seems like `ResourceCover` may replace `Cover`, and users could potentially add it multiple times to a JIG? If true, then I don't think that that constraint is necessary anymore.

**Comment by MendyBerger** [comment]
Good catch, the first module can be any type of module now

**Comment by RickyLB** [comment]
@johnnynotsolucky Good looking out! I'll add a migration to drop the constraint.
