### ISSUE TITLE
Reorganize settings in video module

### ISSUE THREAD

**Issue by MendyBerger** [ji-devs/ji-cloud#2096]
Question: "How to play your video:"
Options: autoplay, loop, captions, mute

Question: "Student finishes this activity..."
Options: "by clicking on continue", "automatically after video"

**Comment by MendyBerger** [comment]
@corinnewo we can't have "play on loop" and "automatically after video" at the same time, they're mutually exclusive.

cc @ChaykeeMor

**Comment by corinnewo** [comment]
If the user chooses the setting '"play on loop", can we disable the option 'automatically after video' and leave the 'by clicking on continue' as the chosen option (only option)?

**Comment by MendyBerger** [comment]
Isn't that overly complicated? I think the current way is much simpler both from the coding side and the UX side

**Comment by corinnewo** [comment]
So you want to leave as it is, either automatically continue or loop. No option to click continue. I'm OK with that - @ChaykeeMor, what do you think?

If you play on loop, then clicking the NEXT arrow in the progress bar would take you out of the loop.
If you unselect the continue automatically, then video will stop and wait for you to click NEXT.
If you select 'Continue automatically', it will advance at end of video.

![image](https://user-images.githubusercontent.com/16290361/147641891-3fb20934-4f6b-4a99-ba04-2f4db0d35ed5.png)

**Comment by ChaykeeMor** [comment]
No, I understand the issue, but the solution shouldn't be 'let's just leave it'. We changed it to suit the users understanding of what these symbols mean and how they affect the game play.  Corinne's first  suggestion is definitely best for the user, 'play on loop' should disable 'continue automatically'. Alternatively, we could take out 'play on loop' because I'm not sure what the added value is when you could play it manually however many times you want. In what scenario would the game player watch a youtube video on loop without clicking on continue after the first watch? @corinnewo what do you think?

<img width="787" alt="Screen Shot 2022-01-03 at 11 24 37" src="https://user-images.githubusercontent.com/94056434/147915534-5bba945d-2bc5-437f-8317-c17316180516.png">

**Comment by corinnewo** [comment]
I'm ok with taking out the loop option. Agree with you - user can play again to see video again.

**Comment by MendyBerger** [comment]
So should we go ahead with removing the loop option?

**Comment by MendyBerger** [comment]
Resolved in 05348e0b5
