### ISSUE TITLE
Resource page - needs correct design

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2121]
https://sandbox.jigzi.org/asset/edit/resource-gallery

The gallery page for resources needs to be specific for the resources. PLease see the design that @GaliShapira did here: https://zpl.io/VK3Ol56

**Comment by chayaml** [comment]
What about any of these?

Use our ready made templates to create interactive games that address all
of your students' learning needs!

Choose from a selection of customizable templates and create your own
interactive lessons and games!

Create your own custom made interactive game using one of our templates!

Also, instead of "Create a new Jig", What about "Create your own game!"

**Comment by corinnewo** [comment]
Needs the new design: 

1. Blue header background with white font
2. Take out the text about JIGs
3. Button should say "Add resource" instead of "Create your own".
4. Change "My Recent Resources" to "My Resources" 

![image](https://user-images.githubusercontent.com/16290361/213407808-6cce9185-9c7b-4be8-b029-cc70878e6d08.png)

**Comment by MendyBerger** [comment]
I believe the design has been updated since

**Comment by GaliShapira** [comment]
This is the updated design:
https://zpl.io/O0MNJgY
https://zpl.io/XYZky3l
https://zpl.io/Nwq9Y84
https://zpl.io/L48NBJ7

**Comment by MendyBerger** [comment]
Resolved
