### ISSUE TITLE
Gallery page - listing suddenly shows duplicates

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2260]
I was creating a new JIG called testing my covers, and in the list I see two if them. Also testing new dialog is appearing twice. If I click on them, each opens up a different JIG inside.

![image](https://user-images.githubusercontent.com/16290361/149362499-40a8ad58-6c7c-4b91-a69c-976fdc78a6c6.png)

**Comment by johnnynotsolucky** [comment]
The JIG ID is not corresponding with its jig_data in the /browse response. 

I think that the problem is from the use of [`zip`](https://github.com/RickyLB/ji-cloud/blob/sandbox/backend/api/src/db/jig.rs#L402-L405) in the browse endpoint. It is assuming that for each jig in the iterator, the jig data iterator has the correct data corresponding with the jig. But I think that the `WITH ORDINALITY` clauses ([jig](https://github.com/RickyLB/ji-cloud/blob/sandbox/backend/api/src/db/jig.rs#L334) and [jig_data](https://github.com/RickyLB/ji-cloud/blob/sandbox/backend/api/src/db/jig.rs#L394)) don't correspond between jig and jig_data because ordinality is on each tables `id` uuid record so the `ORDER BY ord` could be shuffling the ordering more.
