### ISSUE TITLE
Add BETA explanation and link on home page to form that collects feedback from users

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2356]
I would like to add in to the home page (the part that I have control over) that Jigzi is a BETA and that we want feedback. I created a form in Hubspot, that we need to connect to. @GaliShapira  had designed the BETA tab, but I would like to have it within the iframe area, probably in the create area to the right of the video. 
Here is the link to Gali's design: https://zpl.io/ag5Z3qM and 
here is the link to the form: https://share.hsforms.com/1pCg45ADPSlCFSiL0NzOYIQ1kii1

Any comments on the form are welcome. @ChaykeeMor , I need a cute text so users will know that we want feedback.... In Web Creator, we had this: **This is a beta version. Click here to report any bugs.** But I would like something more inspiring please!

Connected with ticket #1735

**Comment by ChaykeeMor** [comment]
**Tooltip currently:** 
Title: You are using our beta version.
Body: We would love to hear your feedback, it will help us learn and improve.
Link: Share your thoughts

**Change to:** 
Title: You are using the beta version.
Body: Your feedback will help us improve our platform.
Link: Tell us what you think!

**Form intro currently:**
Jigzi is the new platform being developed by Ji. It is a BETA release. 
We want to hear back from you, our user,  so that we can improve and create the best platform out there! Please use this form to tell us what's wrong and to suggest what you would find useful.

**Change to:**
You are currently exploring the beta version of the Jigzi platform in development by JI. Your feedback is extremely important to us. Telling us about your experience, good or bad, means that we can better understand what is important to you, what we are doing well and where we need to make improvements.

OR: You are currently exploring the beta version of the Jigzi platform in development by JI. Your feedback is instrumental in our journey to become the best Jewish EdTech platform out there.

@corinnewo

**Comment by corinnewo** [comment]
@ChaykeeMor I have updated the form, and used both versions that you suggest - in the follow up email and response on the screen once the form is submitted, I have used the "Your feedback is instrumental in our journey to become the best Jewish EdTech platform out there."

**Comment by corinnewo** [comment]
Created a new ticket completely: https://github.com/ji-devs/ji-cloud/issues/2365
Closing this one in favor of #2365
