### ISSUE TITLE
End of module - what do you want to do next - resize so no scroll

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2385]
It is so annoying that there is this huge image on the screen, and then you have to scroll down to see your actual buttons.
Please either make the image smaller, or resize the whole screen so that buttons are visible without having to scroll.

![image](https://user-images.githubusercontent.com/16290361/153176949-133226a9-da4f-4bf4-b945-257fde3b01f5.png)

**Comment by johnnynotsolucky** [comment]
In card games, we need to be aware of the extra actions so that on smaller screens we still display correctly:

![image](https://user-images.githubusercontent.com/4161106/158129606-3e8577e6-074c-4f11-9d5a-0cf03806e4a9.png)

![image](https://user-images.githubusercontent.com/4161106/158129670-ed08bce0-26ea-437b-b941-c7ede13e4033.png)

@GaliShapira @corinnewo should we redesign this so its more suitable for smaller screensizes? I think that on smaller screens such as ipads/phones, the teacher will _have_ to scroll on this screen anyway. But with the large image, on smaller screens it may look strange:

![image](https://user-images.githubusercontent.com/4161106/158130234-730b27b3-4ff2-436c-a80d-e3b176a83939.png)

**Comment by GaliShapira** [comment]
The original plan was to present the illustration and text first, and then the yellow area with the actions should have appear while the illustration get smaller.

@johnnynotsolucky Can you make the illustration smaller for the smaller screens? or do you need me to show the sizing for the entire screen?

**Comment by GaliShapira** [comment]
@johnnynotsolucky Please see the design for the small screen.
https://zpl.io/r1yRRxD

**Comment by corinnewo** [comment]
@johnnynotsolucky I still have to scroll on my laptop screen to see the captions of the icons. Please make the illustration smaller so that there is no scroll! Thanks!
![image](https://user-images.githubusercontent.com/16290361/160620574-e2269347-4806-4c69-b6f6-19a5c1bcb6d5.png)
