### ISSUE TITLE
Memory Game - add setting

### ISSUE THREAD

**Issue by ChaykeeMor** [ji-devs/ji-cloud#2426]
We are no longer limiting the amount of pairs allowed for card games but memory games can only fit up to 14 pairs. We therefore need to add a setting to the memory game that allows users to decide how many pairs to include [at random] in their game. rollover on setting: Display [dropdown 4-14] pairs. 

<img width="432" alt="Screen Shot 2022-02-17 at 16 30 01" src="https://user-images.githubusercontent.com/94056434/154502729-283cf302-0a0c-416f-a718-aad6c928974c.png">

Not designed yet, but we will also have a warning when copying list-set from another module with more than 14-- receive warning "Memory games can only fit 14 pairs on a page. What would you like to do? randomly generate memory game from pairs/split into multiple memory games/cancel memory game"

@corinnewo just dropping this here so it doesn't get lost. Will come back to this when we implement image-image cards, right?

**Comment by corinnewo** [comment]
@ChaykeeMor I don't think we need a warning as nothing will be cut off. Can save more than 14 pairs, but the limit on screen is 14 pairs, so each game will simply take a random sample of the possible pairs of cards.
But we will get back to this once Gali has completed the design for image-image use case.

**Comment by ChaykeeMor** [comment]
'Warning' may not be the right term but the point is our users need to know at this juncture that the system can either take random pairs from their list or split their list.

**Comment by corinnewo** [comment]
@johnnynotsolucky Here is the setting we spoke about. Don't put in any warning. I also think that if there are less than 15 pairs, then the default value should be the number of pairs that exist. ie if there are 5 pairs, then the default value would be 5. More than 14, then default value is 14.

**Comment by johnnynotsolucky** [comment]
This is done in #2564.

@GaliShapira, I made it possible to de-activate/activate the setting so that it either uses the amount of pairs the teacher has created (up to a max of 14), or the teacher can specify an amount of pairs to display (between 2 and 14). However, the graphics for the inactive and hover states didn't exist before so I went and added them, but they don't quite match up with the borders of the other settings icons for inactive and hover.

The files are on dropbox at `ji-cloud-media/ui/module/_common/edit/widgets/sidebar/settings/icons`:

- n_pairs-active.svg (this existed)
- n_pairs-hover.svg (I added)
- n_pairs.svg (inactive state, I added)
