### ISSUE TITLE
Jigzi/ legacy player: timer in Jitap doesn't appear in Jigzi

### ISSUE THREAD

**Issue by chayaml** [ji-devs/ji-cloud#2452]
Ji Tap has several "beat the clock" games with a set up timer. This feature did not convert into the Jigzi player. Is it possible to add it?

![Screen Shot 2022-02-23 at 5 14 32 PM](https://user-images.githubusercontent.com/78186896/155349003-6d10eee4-53ed-4dc1-9ff7-820eb53ccd24.png)
![Screen Shot 2022-02-23 at 5 19 23 PM](https://user-images.githubusercontent.com/78186896/155349105-fceed7e8-3ce3-4fd6-86a2-552d0fa1347e.png)
https://jigzi.org/admin/curation/d5696928-69be-11ec-ab82-7fb3593baae4
https://jitap.net/activities/g344/play/

**Comment by corinnewo** [comment]
We have a timer developed for Jigzi. @dakom Please check why this is not working in converted games.

**Comment by dakom** [comment]
@corinnewo we spoke about this before, though I don't see it written down anywhere... I'll add a quick note to the "quirks" doc

We had to drop this (as well as other parameters in the top-level "quizParameters" setting, like "globalLivesLimit"), because it has no mapping to jigs.

We had a lot of back-and-forth about how timing would work in Jigzi.

Imho the Jigzi model of keeping timing per-module instead of per-jig is the correct one. It doesn't make sense to have a Jig composed of a memory game, poster, video, and flashcards and assign a global time limit to it all. Having the timer for memory game alone makes much more sense.

If Jigs end up getting a global timer one day, I might be able to lend a hand in populating that setting for legacy jigs too (that is, jigs that are composed of legacy _modules_ and happened to be converted from TT. There's no such thing as a legacy jig).

Until then, please unassign me from this issue, there's nothing I can do about it.

**Comment by corinnewo** [comment]
@dakom Thanks David - makes sense. I think that this quiz works ok without the timer, but it definitely needs the music, which hopefully will be sorted out with the next merge. I will unassign you for now!

**Comment by corinnewo** [comment]
@chayaml We will just have to work with what we have at the moment, and all those 'beat the clock' games will just be a series of questions and answers. I hope that the music will be working soon, though. It certainly adds to the atmosphere!
