### ISSUE TITLE
Jigzi player: Text/ images expanded beyond canvas area

### ISSUE THREAD

**Issue by chayaml** [ji-devs/ji-cloud#2471]
Hi @dakom here is the info you requested in #2456:

> Yikes.... these seem really, really gnarly. I can't say for certain what's going on here, or if it'll require game conversion.
> 
> @chayaml - can you please do me a favor to make it a bit easier:
> 
> Confirm that in all these cases it's text, not like photos or clipart

In the first link below the entire cover is oversized and in the last link there is an expanded image/animation (p2) so I am really not sure if these quirks are consistent or if they all involve the same issue

> Close all the issues that were opened and are really 1 issue

done
> Create one issue - and in that issue provide the links to the examples you've seen so far.
https://jigzi.org/admin/curation/7efa89a6-69c2-11ec-ab82-33693acdeea0
https://jigzi.org/admin/curation/589664fa-69d2-11ec-8bed-77e56ebff23a
https://jigzi.org/admin/curation/750fd720-69d1-11ec-a181-cb0699d43ddd
https://jigzi.org/admin/curation/b15ae928-69bc-11ec-a962-d71c0d80b2a2

Please let me know if I can clarify anything else!

**Comment by dakom** [comment]
Text in tiny tap seems to always be rendered at half size
Background images too, maybe

the lightning gif is super weird, since the other animations are correct... I think it might just have to be re-transformed by hand, don't think I can fix it programmatically within a reasonable timeframe.

Notably, the original was very transformed.. it's possible that it's somehow corrupt in a way that gets lost in our mathematical conversion (TT just saves the regular transform matrix and passes it through, we convert it to a proper 3d matrix before displaying)

If there are more issues to try and compare what happened, then I'd say it could be worth investing engineering effort- but otherwise, if the user somehow like inverted the axes or did some weird shear thing, I don't think it's possible to mathematically reverse across the board

**Comment by dakom** [comment]
Text would ideally require going back to the source data, but it turns out the filenames consistently seem to have a `_txt` in their name, so I am going to do that as a hacky workaround.

Closing this issue (in sandbox, won't appear until that's merged to master) - but somebody should go in and manually futz with the lightning image to make it look correct. I could maybe help with that but it should be opened as a separate issue of manual design work or json editing, not via programming.

**Comment by dakom** [comment]
game id: 39
