### ISSUE TITLE
Beta version popup - needs more explanation

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2488]
@ChaykeeMor Need your help here, please!

At the moment we have this on our home page: 
![image](https://user-images.githubusercontent.com/16290361/156543507-fc03b828-5c51-4499-bb2b-ea46da8711da.png)

Sammy raised a point yesterday that people may not know what BETA means.  Opening up the popup does not explain anything further!

We thought of maybe changing the heading of the yellow popup to something like "You are using the first version of Jigzi" and to add something like "We couldn't wait for you to start using Jigzi! This is not a full version yet - we have a lot exciting modules more planned for you! Please be patient, and tell us what you think so far!"

Probably needs to be much shorter, but that is the main idea - to explain that Beta means it is the first release.... Thanks

**Comment by ChaykeeMor** [comment]
I actually think it makes us look less serious to accommodate those who don't know what 'beta' means by dumbing down our language in this instance. They could google it. For sure we can't change the 'beta version' label. If we're talking about just the popup, we could make it a little better.. how about..

Top: Thanks for using our beta version!

Bottom: We gave you access to our pre-release version because we couldn't wait for you to start using Jigzi! Your feedback will help us improve. 

link: Tell us what you think so far!

**Comment by corinnewo** [comment]
@ChaykeeMor That's fine! Thanks. I think it does add a little more of an explanation that this is by far a complete product....

**Comment by corinnewo** [comment]
Please change the text in the Beta popup to:

Top: Thanks for using our beta version!

Bottom: We gave you access to our pre-release version because we couldn't wait for you to start using Jigzi! Your feedback will help us improve.

link: Tell us what you think so far!

**Comment by mastapegs** [comment]
Look into having popup open by default initially

**Comment by MendyBerger** [comment]
I think we should also make clear that the application is still buggy

**Comment by MendyBerger** [comment]
> Look into having popup open by default initially

Or open automatically a second after the user opens the page

**Comment by corinnewo** [comment]
We can’t leave it that it opens every time. I’m seeing this pop up as I search…. Should only be open first time. All other screens it is closed. 

Sent from my iPhone

Corinne Ossendryver
CPO, Jewish Interactive 
(+27) 079-8865326
