### ISSUE TITLE
iPad/phone (Safari?) - Player still has PLAY BUTTON at the start of every activity

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2558]
@johnnynotsolucky I know you were looking into this, but it is still not working. I could not find a ticket, as I think we just slacked about it. So I am opening a ticket  - it is still not working.... have to click play each activity.

**Comment by johnnynotsolucky** [comment]
@corinnewo I have looked into it, but forgot to get back to you about it. Autoplay is blocked on all browsers until the user interacts with the application (https://developer.chrome.com/blog/autoplay/). However, each part of a Jigzi game is in an iframe. For example, when a JIG is loaded, the first module is loaded inside an iframe, once the student has completed that module and navigates to the next module, a new iframe is loaded, and so on.

An iframe is a brand new application context in a browser, so iframes need to specify that autoplay can be passed down from the parent context. This works well in Chrome using the [autoplay Feature Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Feature-Policy/autoplay), however in Firefox, that feature is disabled _by default_. It is also not supported by Safari (OSX and iOS), which is why each module in a JIG shows the play button. See [compatibiliity](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Feature-Policy/autoplay#browser_compatibility).

This is a security feature in browsers, and there is no way to work around it in the apps current state. To resolve this issue though, we would likely need to update the JIG player so that each module is loaded as part of the JIG, as apposed to inside an iframe. That would mean that once the student clicks the play button the first time, an interaction has happened, and all audio will play for the rest of the JIG.

To update the JIG play like this is a large change to the fundamental architecture of the application and I _think_ it is a huge change. I haven't looked too much into how this works yet, so I'll have a look and revert back.

Perhaps @MendyBerger has some insights too?

**Comment by corinnewo** [comment]
I tried opening Jigzi on my iPad through Chrome instead of Safari, but it seems that each module still has the play button, even in Chrome on iPad.

**Comment by johnnynotsolucky** [comment]
@corinnewo that makes sense... Chrome on iOS is still actually Safari, just made to look differently. The same applies for FireFox on iOS.
