### ISSUE TITLE
Grid while creating - needs to be symmetric

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2770]
Currently, the grid is difficult to work with to see where the center of the screen is.
Please change the grid to make it clear where the center is, elongate the horizontal squares, so that it is symmetrical. The vertical squares are fine.

**Comment by corinnewo** [comment]
Closing in favor of duplicate of #2764.

**Comment by GaliShapira** [comment]
Hi, I reopened this issue as we are changing the image of the grid. 
The idea is to show instead of the frame the panel buttons.
This is the idea, Merav will upload the final design.

<img width="919" alt="Screen Shot 2022-06-09 at 14 12 45" src="https://user-images.githubusercontent.com/88834002/172833924-96075ac2-59dd-4a70-aa5f-6b6cc2eb0469.png">

@meravs , Can you upload here the new image?

**Comment by meravs** [comment]
screen shot
![Screen Shot 2022-06-09 at 15 26 33](https://user-images.githubusercontent.com/96105053/172846715-66459d09-e68b-4dc5-a1bb-5aad00c40677.png)
e

link to zeplin
https://zpl.io/an3RQKO
![Grid when adding a sticker](https://user-images.githubusercontent.com/96105053/172846919-5e59480d-606f-486c-b8f0-e1bedfc82893.png)
![Grid when adding a sticker](https://user-images.githubusercontent.com/96105053/172846934-d31f77c0-645a-49a8-abc6-2bda5bfdc184.svg)

**Comment by corinnewo** [comment]
@GaliShapira I thought that we said that the blue was too strong - can we make it less intrusive?

**Comment by GaliShapira** [comment]
@corinnewo 
We made the dotted lines more transparent. 
We dont know on which background we see it, we checked a few backgrounds. 

@MendyBerger  Pls see the updated images attached, SVG and PNG options:
![grid](https://user-images.githubusercontent.com/88834002/172887660-070d6fcf-d10c-43c8-8b85-8f45ea30f4f3.png)
![Group 19306](https://user-images.githubusercontent.com/88834002/172887678-3062d128-ef2d-4c82-aa5d-e84b86fb096c.svg)
