### ISSUE TITLE
Ipad - player - extremely tiny preview... Cant play a JIG

### ISSUE THREAD

**Issue by GaliShapira** [ji-devs/ji-cloud#2904]
Well, this is a top priority to fix...
Cant play a Jig...
![IMG_0294](https://user-images.githubusercontent.com/88834002/178466628-77d14149-6d65-49cd-bc83-3fb20427e767.PNG)

**Comment by corinnewo** [comment]
@GaliShapira This is interesting, as this has happened to a few users, but on our iPads it looks fine. So now, if it is happening on your iPad, we have a device to test and debug on. I agree, it is useless like this!

**Comment by MendyBerger** [comment]
This is most probably because Safari is not up to date (awaiting confirmation from @chayaml).

Since we keep on having issues because of outdated browsers, maybe we should try to detect that users are on outdated browsers and show a popup letting them know that we don't support their browser and they might experience some issues, though I'm not sure how easy it's going to be to detect that.

Would be especially useful on Safari as it tends to lack behind others and is not as easy to update as the others.

**Comment by GaliShapira** [comment]
After updating the system update, it is better.
The frame for the JI-TAP games is very small.

![IMG_0326](https://user-images.githubusercontent.com/88834002/182603328-f805bfe4-6fd6-4e1e-853f-dde8ae7ed3a5.PNG)

**Comment by MendyBerger** [comment]
Seems like the original issue is resolved now, if you wanna discuss the size of the legacy games we can do that in a dedicated issue
