### ISSUE TITLE
Answer This: Contents of question box must show on the canvas for each question

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3085]
Because of user feedback, we need to refine this interaction.
Problems:

1. Teachers did not know that their typed questions would appear automatically on the screen, and so the questions cover the content
2. Teachers did not know that if they selected the question box, then their questions would appear in that box, could be styled, resized, or repositioned.
3. Very confused by this until they worked out where the written questions appear.

Solution discussed by Corinne and Anat, then refined with Tyrone:

- [ ] On first screen of the tab, can choose between adding a new question or choosing a text box. Currently when you choose a new question, there is no question box that you can style or see on the canvas, and when you preview, you see it as an automated text that you cannot position or style.
Solution: When you click the +new question, it will insert a question box onto the canvas that will be empty. Question box should have a slightly different border. (even if you chose a question already on the screen, that border should change)
![image](https://user-images.githubusercontent.com/16290361/185571707-16f539d9-4033-4844-8892-f7cbb9c006eb.png)

- [ ] When you type in the question tab, the text will appear simultaneously on the canvas, in the question box. (QUESTION - IF YOU EDIT IN THE QUESTION BOX, WILL IT SHOW ON THE QUESTION TAB?
![image](https://user-images.githubusercontent.com/16290361/185572191-0c5c1b37-e2ec-4656-92ee-83331318c80c.png)

- [ ] If there are **any** typed questions, the DELETE on the question box will be disabled. 

- [ ] If you go back to the content tab with a new question box, then it will show it, but with text 'Your question box', in the font and style that you have chosen in the interaction.

**Comment by johnnynotsolucky** [comment]
@corinnewo 

> Solution: When you click the +new question, it will insert a question box onto the canvas that will be empty. Question box should have a slightly different border. (even if you chose a question already on the screen, that border should change)

This shouldn't be difficult. We'll need to add a new text sticker with default text such as "Your question box" to the list of stickers on the activity.

> When you type in the question tab, the text will appear simultaneously on the canvas, in the question box. 

We can reuse the code I added to set the text when a student is playing the activity. We need to add an event handler to update the text as the teacher types/clears text in the question text field. 

> QUESTION - IF YOU EDIT IN THE QUESTION BOX, WILL IT SHOW ON THE QUESTION TAB?

I think that we shouldn't do that. The code to implement this will be quite complex. Perhaps we should disable editing when the teacher is working on questions?

> If there are any typed questions, the DELETE on the question box will be disabled.

We will need to update the [Text](https://github.com/ji-devs/ji-cloud/blob/sandbox/frontend/apps/crates/components/src/stickers/text/state.rs) state to include can_delete and can_edit fields so that we can enable/disable the items in the menu.

> If you go back to the content tab with a new question box, then it will show it, but with text 'Your question box', in the font and style that you have chosen in the interaction.

Whenever a teacher navigates away from the questions in interaction (closes all questions or changes to another step), revert the text in the sticker to "Your question box". Will use the same logic to change the text when editing questions.

I think that this could be completed in a couple of days. Overall it is not too much work, and for a lot of it there is existing logic that we can use.

However, we do need to highlight the text sticker which is set as the question box. We will need to have a separate _new_ border around the text, instead of updating the existing one. The current border is part of the transform controls, and is used for resizing, moving, etc. If we had that visible all the time, it would change how teachers interact with stickers. I think that this part of the task might take a bit longer to implement.

**Comment by corinnewo** [comment]
Great. Thank you. So the question is whether to go ahead now, or continue with the august small tickets? Let’s discuss on Monday!

Sent from my iPhone

Corinne Ossendryver
CPO, Jewish Interactive 
(+27) 079-8865326
