### ISSUE TITLE
Drag and Drop: dragging an incorrect item causes screen to freeze

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3117]
https://jigzi.org/asset/play/jig/afb9b7e0-2634-11ed-8580-57a5558e8aad?direction=ltr&display_score=false&track_assessments=false&drag_assist=false&is_student=false&draft_or_live=live

PLease take a look at screen 03, for example.
If you  try to drag in a wrong letter, it highlights the wrong letter and the trace area, and then it gets stuck....

**Comment by johnnynotsolucky** [comment]
@corinnewo the highlighting issue is fixed in #3118. However, the underlying issue was that the incorrect stickers in that activity were not marked as interactive and therefore students wouldn't be able to drag them. They're just visual elements on the screen.

I wonder if we should update the wording or instructions to indicate that _any_ sticker which can be dragged around should be selected as an interactive sticker?

**Comment by corinnewo** [comment]
I think that you are right. We need to add in to the Jiggling text, and possibly in the instruction. @ChaykeeMor - We need your input here please!
