### ISSUE TITLE
Ji tap legacy - 2 cases where the click an item to jump to another screen are not working

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3311]
Edward pointed out 2 places that the imported Ji TAP games are not working as they should be:
1. https://jigzi.org/asset/play/jig/36af19a6-b91c-11ec-8c17-237d9061d376?direction=ltr&display_score=false&track_assessments=false&drag_assist=false&is_student=false&draft_or_live=live screen 10. Supposed to click the kamatz katan to find out more - nothing happens when you click.
![image](https://user-images.githubusercontent.com/16290361/198578631-6ecd6372-dbae-4597-812a-6b474457cca9.png)

2. Screen  20 - supposed to click the purple cylindar to bring it into place. Click it and nothing happens.
![image](https://user-images.githubusercontent.com/16290361/198578518-262d7433-63e1-4452-bf63-8f0ba008958f.png)

**Comment by corinnewo** [comment]
I'm worried that this is happening in other places too, where the clicking an object to continue is not working.

**Comment by dakom** [comment]
the first step to debugging this would be to see the original tiny tap JSON and look at what the value there is.

can you share the Game id and slide number?

**Comment by dakom** [comment]
### SHORT VERSION:

Can confirm that this is a difference compared to tiny tap player: https://jitap.net/media/webplayer/webplayer.html?structureJson=https://jitap.net/store/api/album/18110/structure/

BUT - you click _anywhere_ ... it is not a hotspot
AND - it merely goes to the next page.

@corinnewo - It would help if I can get a bit more info... can you please check if these and other cases are all where it uses the "tap anywhere to advance to next screen" functionality? (they probably call it something different in the UI)

If that's the case, I think I see the bug, and if so it's almost definitely something I can fix on the player side without needing to re-generate the games

### LONG VERSION:

game id: 18110
slide id: photo30

our generated JSON: https://legacy.jicloud.org/transcode/games/18110/json/slides/photo30.json

there is no hotspot.

*same in the Tiny Tap JSON*

they don't break it down by slide, but in https://jitap.net/store/api/album/18110/structure/

we can navigate to the same slide id section:

```
{
          "layers": [
            {
              "InteractiveLoopType": 0,
              "InteractiveShowType": 0,
              "frame": "{{0, 0}, {2048, 1536}}",
              "transform": [
                1,
                0,
                0,
                1,
                0,
                0
              ],
              "filename": "1_bg.jpg",
              "width": 2048,
              "height": 1536,
              "type": "bg",
              "interactiveToggleShow": false
            }
          ],
          "activities": [
            {
              "recordingDuration": 8.064,
              "filePathIntroRecording": "photo30/activity0/activity0.mp3",
              "settings": {
                "advance": false
              },
              "shapes": [
                
              ],
              "pk": 629490,
              "folderPath": "photo30/activity0"
            }
          ],
          "filePathImageThumb": "photo30/photoThumb30.jpg",
          "filePath": "photo30/",
          "filePathImage": "photo30/photo30.jpg",
          "pk": 858525,
          "engineType": "R"
},
```

Notice that there are no hotspots defined

However, they have `advance: false`... which may mean _auto-advance_ is false... and when we look at our JSON, it seems we respect this setting:

```
advance_trigger": "tap"
```

So the bug is probably just on the player side, not acting on `advance_trigger`

**Comment by corinnewo** [comment]
I'm happy to just have the click anywhere to advance option, as long as it goes to the next screen when there is a click! That's great if you can fix it on the player.

**Comment by dakom** [comment]
@corinnewo this is fixed in https://github.com/ji-devs/ji-cloud/pull/3509

Problem: an html layer was grabbing pointer events and stopping the background layer from detecting clicks, while the logic of "move to next" is driven by background clicks in this case

Solution: this seemed to be an issue specific to "say something", and so the say something foreground layer simply has pointer events disabled now.

**Comment by corinnewo** [comment]
@dakom This seems to be working now! Thanks!
