### ISSUE TITLE
Legacy game - Clips not loading on pc, but works on iPad

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3457]
Clips are not loading on screens 4, 7, 10, 14,17, etc

https://jigzi.org/asset/play/jig/82417624-69bd-11ec-9193-fb4a1ea51eee?direction=ltr&display_score=false&track_assessments=false&drag_assist=false&is_student=false&draft_or_live=live

**Comment by dakom** [comment]
Ok, yes, I see.... this is a bit of a mess:

1. in the cloud storage there is `/games` and `/transcode/games`. I think `/games` are old and out of date, and rather everything is now loaded from `/transcode/games`. So `/games` should actually be deleted

2. however, it seems that the earlier version did _more_ to transcode media. Specifically, in this case, there is a mp4 version of the mov file in `/games`, but not in `/transcode/games`

Re-processing all the games, especially since this is not in the newest set, is just not realistic at this point in time. However, I think this can be solved by doing the following:

1. Spin up a cloud instance
2. Sync the cloud storage into a local dir on the instance
3. Write a tool that will crawl for the media files by the directory contents (not parsing the JSON - neither jigzi version nor tiny tap, just the raw media files)
4. Transcode
5. Re-sync back

**Comment by dakom** [comment]
`/games` should be completely deleted as well

**Comment by dakom** [comment]
Deleting `/games` now. Will need to look at solving this later

**Comment by dakom** [comment]
Finished this process. Should now be fixed - @corinnewo please confirm :)

**Comment by dakom** [comment]
@corinnewo is this still broken for you?

**Comment by corinnewo** [comment]
It is working for me. I will close now, but we have received a few complaints from users about the clips not working. These same JIGs have worked for me. So closing, but might need to reopen!
