### ISSUE TITLE
Legacy game: Voiceover timing issue

### ISSUE THREAD

**Issue by chayaml** [ji-devs/ji-cloud#3464]
The voiceover plays at the wrong time in the matching game - in JiTap it plays when revealing the card, but in Jigzi it only plays after hiding the card.

To reproduce:

1) Go to third menu item
![Screen Shot 2022-12-14 at 10 50 56 AM](https://user-images.githubusercontent.com/78186896/207645486-9f46d86d-d98e-4e4e-9f47-3f5a0e4f1845.png)
2) Move forward four slides
![Screen Shot 2022-12-14 at 10 51 41 AM](https://user-images.githubusercontent.com/78186896/207645554-63e430c8-1059-4c20-9de5-902fe5df2769.png)
3) Also occurs in the fourth menu item

JiTap Link:
https://jitap.net/activities/gfcx/play/
Jigzi Link:
https://jigzi.org/admin/curation/0537ce72-7983-11ed-9c12-df2678e188ff

**Comment by corinnewo** [comment]
https://jigzi.org/asset/play/jig/0537ce72-7983-11ed-9c12-df2678e188ff?direction=ltr&display_score=false&track_assessments=false&drag_assist=false&is_student=false&draft_or_live=live

**Comment by corinnewo** [comment]
Here is another example of the sound and Houdini not playing the sound. Slides 4 and 5 in
https://jigzi.org/asset/play/jig/c422c3ae-69c7-11ec-841b-9f15c9b0b5fc?direction=ltr&display_score=false&track_assessments=false&drag_assist=false&is_student=false&draft_or_live=live

**Comment by corinnewo** [comment]
Houdini sound plays only after you click the card a second time.

**Comment by dakom** [comment]
@corinnewo this is fixed in https://github.com/ji-devs/ji-cloud/pull/3509

Problem: in tiny tap the sound plays also while _hiding_ an image, and this game is actually setup such that you _hide_ the cards. in jigzi sound only played while _showing_ an image, and so things were basically inverted and broken

Solution: play sound whenever visibility is toggled, whether showing or hiding

Caveat: the fix is currently only applied to static images. not animation. further discussion on Slack
