### ISSUE TITLE
Houdini animations  not working

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3469]
This game
https://jigzi.org/asset/play/jig/14cb6bc8-7983-11ed-8ebc-6f8ad4113279?direction=ltr&display_score=false&track_assessments=false&drag_assist=false&is_student=false&draft_or_live=live
still not working on Jigzi 
slides 25,29,30,31 - Animation not working 
 Slides 16,18,32,34,40,43 the END icon doesn't work

**Comment by dakom** [comment]
Is the "animation not working" purely a duplicate of https://github.com/ji-devs/ji-cloud/issues/3458 ? i.e. it's a houdini issue?

If so - can you please close that one or this one, and edit the description to include the additional problematic slides?

In terms of end icon not working - if you look at the game JSON, it links _past_ the end slide.

In more detail, looking at around slide with layer `photo25` in this game JSON: https://legacy.jicloud.org/transcode/games/18864/json/game.json

Every index in the original JSON is actually offset by 1 due to the first cover page. So the link to `1` actually goes to slide number 2 (and this works correctly), and the link to `44` actually goes to slide number 45 **but there is no slide 45.**

This information is _lost_ at transcoding time. I could rewrite the tool to say "any jump index 1 past the end should go to the end", but this change will only be for the latest batch of imports, not all jigs in the system

**Comment by corinnewo** [comment]
We have only seen this problem with the end icon so far in one lesson. Could we fix it manually?

**Comment by dakom** [comment]
Yes, it can be fixed manually - but it needs to be done at each hot spot and in each slide

For example in https://legacy.jicloud.org/transcode/games/18864/json/slides/photo25.json it would need the second hotspot to have a `"jump_index": 43` like how the first hotspot has `"jump_index": 1,`

Probably better for me to fix it on the tool level

**Comment by corinnewo** [comment]
another example of sound problem in Houdini: slide 24 on https://jigzi.org/asset/play/jig/0537ce72-7983-11ed-9c12-df2678e188ff?direction=ltr&display_score=false&track_assessments=false&drag_assist=false&is_student=false&draft_or_live=live

**Comment by dakom** [comment]
@corinnewo - thank you! that's very helpful for when I can get to debugging this, since I can clearly see that the audio files are in the metadata: https://legacy.jicloud.org/transcode/games/18671/json/slides/photo14.json

there's obviously something wrong in my player logic for houdini stuff

**Comment by corinnewo** [comment]
Yes - it seems to be working. I can jump to the end and it goes to the end!
Now to fix the Houdini! Thanks!

**Comment by dakom** [comment]
@corinnewo this is fixed in https://github.com/ji-devs/ji-cloud/pull/3509

Sound and jumps were addressed elsewhere. In terms of the visibility of houdini itself, i.e. matkot:

Problem: toggling logic pierced through all layers of animation. This game was setup such that each layer actually hides the one beneath it, so they all start off visible, and then only the top layer is meant to toggle and reveal the one beneath it.

Solution: basically emulate a html event propogation stack. Top layer can stop the "piercing" mechanism of layers below it.

Caveat: no known issues atm, seems like it was just a misunderstanding of how things were supposed to work, but this is a fundamental change (in fact it begs the question, why not just use regular html for this). I'm a bit concerned that this didn't break something else. This should probably be QA'd a bit more with test cases to be sure nothing broke

**Comment by dakom** [comment]
@corinnewo - is there anything left to do on this issue, or is it fixed?

**Comment by corinnewo** [comment]
@dakom I think that this is working well, thank you! They are playing matkot! I have also checked in my Alef-Bet games where the Houdini played such an important role, and they are working well. I will close this ticket now. Thanks!
