### ISSUE TITLE
Image Admin: add Expand All / Collapse All to categories

### ISSUE THREAD

**Issue by dani-ji** [ji-devs/ji-cloud#371]
- [ ] When in the image edit page the search bar to find the correct category does not work 
- [ ] Placeholder text is incorrect and should say Category Search
![Category Search](https://user-images.githubusercontent.com/73904351/99541465-d91b5f80-297e-11eb-8e0d-4d3086555f79.png)

@corinnewo

**Comment by dakom** [comment]
Is "search" here more like a local simple text matching that will auto-expand categories containing that text?

If so, what is it supposed to do in the following scenario:

1. manually expand a bunch of categories
2. enter something in the text field

Does it close all the categories that were previously expanded, and now only expand the ones they've searched for? (e.g. it will collapse whatever they previously had open)

**Comment by dani-ji** [comment]
@corinnewo please advise

**Comment by corinnewo** [comment]
It is a search within the category tree, locally on this image page.
I think it should find the instances of the word, expand those branches, and highlight the word. Ideally, it should find first instance and highlight, then if search again, show next instance.  It does not enter something in a text field. Simply opens up so that user can find that subcategory easy, and then be able to select that node if required.
Regarding collapsing any open categories, it probably is a good idea, as then you can focus on the expanded branch and focus on the result.

**Comment by dakom** [comment]
alternative idea: "expand all" and then they can use their browser's control-f to navigate around

**Comment by corinnewo** [comment]
That’s a reasonable solution in the meantime!

Sent from my iPhone

Corinne Ossendryver
CPO, Jewish Interactive 
(+27) 079-8865326

**Comment by dani-ji** [comment]
@dakom was this merged? I still see the image search and no expand all

**Comment by dakom** [comment]
it's on sandbox, not release yet, will merge to master with some other stuff a bit later and ping you on slack

**Comment by dani-ji** [comment]
@dakom 

- [ ] it appears some of the categories are displaying differently

- [ ] The next button does not seem to go to bottom of page, not sure if this is intanial

Please assign to @NaomiLea if these are for her
