### ISSUE TITLE
Sign Up - Unknown Firebase error on Send Email Confirmation page

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#422]
**Describe the bug**
When I click "I didn't receive an email, Please send again" I encounter an "unknown firebase error"
https://www.loom.com/share/b1e9e820fb6a4f2d80559decd105256e

Additionally, if I refresh the page, I run into a "no auth" wall
https://www.loom.com/share/a276b7f464354cd4bd8b4744b4ab1167 

**To Reproduce**
1. Move through Sign up process in Registration flow
2. Arrive https://jicloud.org/user/send-email-confirmation  
3. Click "I didn't receive an email, Please send again"
4. **Sometimes** see error

**Expected behavior**
Email resend notification or refreshed page

**Screenshots**
see above

**Additional context**
This does not happen every time. After my first screen record of the Unknown Firebase Error, the button worked as expected (ie I got notification for email resend), but then it stopped working again.

**Comment by dakom** [comment]
Going into the network tab in the dev console and clicking on the error shows it as `TOO_MANY_ATTEMPTS_TRY_LATER`

![chrome_Pags2vEk7e](https://user-images.githubusercontent.com/6406986/100328063-c33c1900-2fd4-11eb-8c15-883843b25031.png)

According to the firebase docs, this may be due to "unusual activity":

> We have blocked all requests from this device due to unusual activity. Try again later.

- https://firebase.google.com/docs/reference/rest/auth

With that in mind... I'm not sure what we can do here. It may be due to firebase knowing that the email address itself is potentially a spam attack, in which case we _want_ to prevent it (perhaps showing a nicer error message though)
