### ISSUE TITLE
Categories - Add "Categories search" + fix "Add category" spacing

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#476]
Categories pages are missing the "Categories search" after the page heading. Additionally, the "Add category" button looks like it should be further to the right. Please implement the following changes:

(1) Add "Categories search" after page heading.
(2) Make sure the "Add category" is properly positioned. **Note:** This may be resolved by adding the "Categories search" field. 

Zeplin sketch for anticipated layout: https://www.loom.com/i/7e882175a2e74b24916dff4bf141b8ef 

Ji Cloud for current layout: https://www.loom.com/i/f0c42dab741946c8802c649f66a12a21

**Comment by dani-ji** [comment]
@corinnewo I know we got rid of search in place of expand all, is there a need for expand all on this page as well?

**Comment by corinnewo** [comment]
@dani-ji It would be useful to have the expand all functionality to be able to find a category, in case you need to edit something. If it does not take a huge amount of time to add an EXPAND ALL/COLLAPSE ALL to this page, I think it would be helpful.

**Comment by dani-ji** [comment]
@dakom would it be a large effort to add expand all to another page or once the function has been written we can easily reutilize?

**Comment by dakom** [comment]
it's totally proprietary to the image page, because it's not just the tree itself - the state of that tree has to push for live saving as well as impact a separate culled display

that said, if we do need a generic tree thing that doesn't have those features, it would be not too hard to use this as a starting point and hack away from there

alternatively, adding a proprietary expand/collapse all to this page might be easy too (can't remember offhand)

**Comment by dani-ji** [comment]
@corinnewo given that this will take some amount of time though unknown how much, is it high, medium or low priority?

**Comment by corinnewo** [comment]
Low priority!


Sent from my iPhone

Corinne Ossendryver
CPO, Jewish Interactive 
(+27) 079-8865326

**Comment by dakom** [comment]
@corinnewo approved to just close this... "expand all" + browser's native ctrl-f search is fine
