### ISSUE TITLE
Sign up - Step 3: Order in age-order

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#480]
Step 3 of sign up process lists ages out of order.
See Zeplin Sketch for anticipated order: https://www.loom.com/i/735aaf2f05f14d2597e10e0805412291 
See Ji Cloud for incorrect order: https://www.loom.com/i/cc08e390d2984d7e88a45c529b9b3a9c 

Please reorder according to age order. 

Per instructions from Corinne, should be:
All ages
Kindergarten
Elementary school
Middle school
High school
University

**Comment by NaomiLea** [comment]
This has been rebuilt and is correct on the new version

**Comment by esteels** [comment]
@NaomiLea reopening for minor text edit.

Please change text of "Elementary" to "Elementary school"

**Comment by dakom** [comment]
Just a note - discussed on a recent zoom call, @esteels is 100% right to re-open and point this out, but at the same time these are one of those things which are populated on the DB and fixing it in Storybook is _not_ a guarantee that it is fixed in the live version (in fact, fixing it on `sandbox` isn't even a guarantee that it is fixed on the `release` site), which is perhaps why less attention was paid in both Zeplin and Storybook (since they are merely placeholders)
