### ISSUE TITLE
is there a UI for error when they hit "continue" but haven't checked "I am over 18"

### ISSUE THREAD

**Issue by dani-ji** [ji-devs/ji-cloud#659]
is there a UI for error when they hit "continue" but haven't checked "I am over 18"?  https://storybook.sandbox.jicloud.org/?path=/story/full-pages-login--sign-up-one

**Comment by dakom** [comment]
@dani-ji - seems this might not be in Zeplin and needs a reference

**Comment by NaomiLea** [comment]
This has been fixed

**Comment by dani-ji** [comment]
@NaomiLea how do I sample this behavior? I don't see any controls on the screen

**Comment by dakom** [comment]
https://storybook.sandbox.jicloud.org/?path=/story/input-text--checkbox

add text into the `error` control and you'll see it

(note that the storybook url may change when we refactor)

**Comment by dakom** [comment]
@dani-ji more info: the concept is that this "checkbox with a label and potential error" is a _custom element_. Literally it becomes an html element that can be used anywhere (and isn't even framework dependent - e.g. this is _not_ React).  For example it can be used like `<input-checkbox label="whatever" />` or `<input-checkbox label="whatever" error="uhoh"/>` and so on.

We need to test it of course, but since it's completely encapsulated, we only need to test it in _one place_. We do that by creating what we're calling a "component". Note that "component" is a very overloaded term - and so when we talk about it in the context of Storybook, it's basically synonymous with a "Storybook Story, perhaps with Controls".

So the link above is to the _component_ and under the hood it uses the _element_

In pages like user registration, it will re-use that same _element_ (or the same test component which itself uses the same element - boils down to the same thing) - and so _there is no need to test it again_.

In other words, the idea is that we only need controls in storybook to test things that aren't tested elsewhere.

That's really in terms of deployment though. While @NaomiLea is working through a component, it's very likely she'll change properties locally and see how it behaves before feeling confident about pushing it. For example, there's no controls to make sure that the dropdowns at https://storybook.sandbox.jicloud.org/?path=/story/full-pages-login--sign-up-two aren't pushing other boxes down, but conceptually dropdowns should _never_ push other items down - so it's the kind of thing that is better left out of controls and dealt with in an isolated test on the "Dropdown" story, as opposed to on the registration page.

(there isn't actually a test for that on the dropdown component page... would be nice to have but probably not necessary)

This is all about UI though. It's possible for there to be a runtime bug of not triggering the error state when they hit continue and the box is unchecked, but that would be a logic/state bug - not a ui bug, and therefore isn't reflected in Storybook

**Comment by dani-ji** [comment]
Thank you @David Komer <david@jewishinteractive.org> this was very helpful
