### ISSUE TITLE
JSON location

### ISSUE THREAD

**Issue by dakom** [ji-devs/ji-cloud#756]
Ultimately, the JSON files need to be created through a user interface that any admin can use. 

This means the tool must support loading that JSON from somewhere other than the binary directory

Here are two approaches:

1. Remote URL. Could be on cloud storage, could be through our backend API. For the purposes of this discussion it doesn't really matter - it's just a URL

2. Dropbox folder (similar to our UI media).

The advantage of the Remote URL is that it's more flexible and a cleaner approach in general. However, the disadvantage is that the tool will not be able to easily run in "watch" mode for local development.

The advantage of Dropbox is that watching and re-running the tool is easier for local dev. However, the disadvantage is that pushing to dropbox from the UI is going to be messy.

My current feeling is that we go the Remote URL route and do watching via some sort of polling mechanism or something, but we should talk it out and of course consider any other alternatives

**Comment by dakom** [comment]
Decided it will be Remote URL (which effectively covers the Dropbox use-case too if we need it)

**Comment by MendyBerger** [comment]
Added in https://github.com/MendyBerger/ji-cloud/commit/49c2c1b81a69907e3da8aab4d54e0287684cb718

I added two new options one for the core json location and another for the entry json location.

To use run `cargo run -- --entry=user --core-location='https://example.com/path/to/core.json' --entry-location='https://example.com/path/to/user.json'`.

I made the json location configurable from outside so that we should be able to eventually add other languages besides English
