### ISSUE TITLE
Publish Page vs Publish on JIG

### ISSUE THREAD

**Issue by dani-ji** [ji-devs/ji-cloud#832]
"looking at the jig screen - I don't see the publish button. met with @corinne and she explained that it's the last item in the panel... this is extremely confusing imho
All of the jig panel items are associated with a "module player" - cover, poster, memory game, tapping board, etc.
There is no "publish" player. As a user, I also don't think I'd ever know that to publish my jig I click on the pencil icon of this module.
suggestion: add a publish button to the top of the page, as well as gear/settings.
5:07
A hardcoded default "last module" makes sense if it was something the user can play... like a "report page" with confetti or whatever, so then in the jig editor you have options to design or edit that module... but if we don't have that, the last module should just be taken out imho (and settings would be set in the top-level jig settings if we have that button)" -David

@corinnewo  please advise decision

**Comment by corinnewo** [comment]
I took it to the ideation team, and they agree with David. We changed the last module to look different and it would hold the settings and publish. I am waiting for the ideation team to approve putting a publish button on the top right of the 'Add an Activity' page, so that people who are coming back to edit and just want to publish again, can easily find the button.
Gali and I discussed 2 use cases:

1. If first-time in the JIG (not published yet), then clicking the PUBLISH button will open up the property settings and then publish.
2. If JIG has already been published, and all you want to do is change something in a module, then you can click the publish button and it will republish.

You can always edit the settings by going to the last module of the JIG and editing.

Waiting for approval from ideation team.
