### ISSUE TITLE
Jig list route for users

### ISSUE THREAD

**Issue by dani-ji** [ji-devs/ji-cloud#963]
When I login I am able to see and edit the JIGs that David has created

Expected behavior would be that I can only see the JIGs I created unless the other user has made them public and I should not be able to edit their JIG

**Comment by dakom** [comment]
Renamed the issue. More detail:

The current list route is an admin route to list *all* jigs. What we need is a route to only list *my* jigs.

It should also allow filtering by whatever's possible without hitting algolia, though for starters we need filtering by is_published.

This is overall similar to the issue with images, i.e. this route is different than [searching](https://github.com/ji-devs/ji-cloud/issues/969) because of how Algolia restricts limits (and also if we don't need to search, why search)
