### ISSUE TITLE
Default first letter in Memory Game

### ISSUE THREAD

**Issue by dani-ji** [ji-devs/ji-cloud#975]
In the first letter memory game template; when a user adds a word the second column should be populated with the first letter from the word by default with the user still having the ability to edit it

example user adds word Ball the first letter column should display B

**Comment by dakom** [comment]
what if they go back and edit the first column?

**Comment by dani-ji** [comment]
@corinnewo os it expected that in the case David mentioned the second column would update?

Is this feature (first letter auto populate) high priority or nice to have

**Comment by corinnewo** [comment]
Nice to have.
I would say that the first letter is set when you first make the list. After that, if you edit, you need to edit both columns, since you make have wanted to change the first letter to something else. Eg, if you want a letter without nikud, and it put in by default with nikud, changes should be kept.

**Comment by dakom** [comment]
Discussed on Zoom - for our audience and use case it's often the case that the teacher wants to take into account nikkud, even using multiple letters (like bet with vav)

Therefore we're not going to do it as a built-in automatic thing. Rather, we'd add an "auto-generate" button so it's an explicit choice by the user.

It was decided not to do this for MVP though...

**Comment by johnnynotsolucky** [comment]
Closing this in favor of #2267
